/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package appgrand_go_kart;
import capaSimulador.Competidor;
 import capaSimulador.Competencia;
 import capaSimulador.Simulacion;
 import appgrand_go_kart.FrmRegistroCompetidor;
import java.util.HashSet;
import java.util.Set;
import javax.swing.JOptionPane;
import capaSimulador.ECategoriaCompetidor;
import capaSimulador.EAsignarEquipos;
/**
 *
 * @author Axel
 */
public class FrmGanadores extends javax.swing.JFrame {
    private Simulacion oSimulacion;
    /**
     * Creates new form FrmGanadores
     */
    public FrmGanadores(Simulacion simulacion) {
        this.oSimulacion = simulacion;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaGanadorGeneral = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txaGanadorCategoria = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        txaGanadorEquipo = new javax.swing.JTextArea();
        btnReiniciar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setText("Ganadores de la Clasica ISW Grand Go-Kart");

        txaGanadorGeneral.setEditable(false);
        txaGanadorGeneral.setColumns(20);
        txaGanadorGeneral.setRows(5);
        txaGanadorGeneral.setBorder(javax.swing.BorderFactory.createTitledBorder("Ganador General"));
        jScrollPane1.setViewportView(txaGanadorGeneral);

        txaGanadorCategoria.setEditable(false);
        txaGanadorCategoria.setColumns(20);
        txaGanadorCategoria.setRows(5);
        txaGanadorCategoria.setBorder(javax.swing.BorderFactory.createTitledBorder("Ganador por Clasificacion"));
        jScrollPane2.setViewportView(txaGanadorCategoria);

        txaGanadorEquipo.setEditable(false);
        txaGanadorEquipo.setColumns(20);
        txaGanadorEquipo.setRows(5);
        txaGanadorEquipo.setBorder(javax.swing.BorderFactory.createTitledBorder("Ganador por Equipos"));
        jScrollPane3.setViewportView(txaGanadorEquipo);

        btnReiniciar.setText("Reiniciar Simulador");
        btnReiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReiniciarActionPerformed(evt);
            }
        });

        btnSalir.setText("Salir del Simulador");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27))))
            .addGroup(layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(btnReiniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 355, Short.MAX_VALUE))
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReiniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(185, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        Competidor ganadorGeneral = oSimulacion.ganadorGeneral();
        ECategoriaCompetidor categoria = oSimulacion.ganadorCategoria();
        EAsignarEquipos equipos = oSimulacion.ganadorEquipo();
        txaGanadorCategoria.append("La categoria ganadora es: " + categoria.name() + "\nCon un tiempo de: " + oSimulacion.ganadorCategoriaTiempo());
        txaGanadorGeneral.append("El ganador general del ISW Grand-Go-Kart es: " + ganadorGeneral.getId() + "\nCon un tiempo de: " + ganadorGeneral.getTiempoTotal());
        txaGanadorEquipo.append("El Equipo ganador es: " + equipos.name() + "\nCon un tiempo de: " + oSimulacion.ganadorEquipoTiempo());
    }//GEN-LAST:event_formWindowOpened

    private void btnReiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReiniciarActionPerformed
        // TODO add your handling code here:
        oSimulacion.limpiarDatos();
        JOptionPane.showMessageDialog(this, "Simulacion reiniciada con exito.");
        this.dispose();
    }//GEN-LAST:event_btnReiniciarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReiniciar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea txaGanadorCategoria;
    private javax.swing.JTextArea txaGanadorEquipo;
    private javax.swing.JTextArea txaGanadorGeneral;
    // End of variables declaration//GEN-END:variables
}
