/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package appgrand_go_kart;
import capaSimulador.Competidor;
 import capaSimulador.Competencia;
 import capaSimulador.Simulacion;
 import appgrand_go_kart.FrmRegistroCompetidor;
import java.util.HashSet;
import java.util.Set;
import javax.swing.JOptionPane;
import capaSimulador.ECategoriaCompetidor;
import capaSimulador.EAsignarEquipos;
/**
 *
 * @author Axel
 */
public class FrmGanadores extends javax.swing.JFrame {
    private Simulacion oSimulacion;
    /**
     * Creates new form FrmGanadores
     */
    public FrmGanadores(Simulacion simulacion) {
        this.oSimulacion = simulacion;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaGanadorGeneral = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txaGanadorCategoria = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        txaGanadorEquipo = new javax.swing.JTextArea();
        btnReiniciar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 3, 24)); // NOI18N
        jLabel1.setText("Ganadores de la Clasica ISW Grand Go-Kart");

        txaGanadorGeneral.setEditable(false);
        txaGanadorGeneral.setColumns(20);
        txaGanadorGeneral.setRows(5);
        txaGanadorGeneral.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ganador General", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Sylfaen", 1, 14))); // NOI18N
        txaGanadorGeneral.setFocusable(false);
        jScrollPane1.setViewportView(txaGanadorGeneral);

        txaGanadorCategoria.setEditable(false);
        txaGanadorCategoria.setColumns(20);
        txaGanadorCategoria.setRows(5);
        txaGanadorCategoria.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ganador por Clasificacion", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Sylfaen", 1, 14))); // NOI18N
        txaGanadorCategoria.setFocusable(false);
        jScrollPane2.setViewportView(txaGanadorCategoria);

        txaGanadorEquipo.setEditable(false);
        txaGanadorEquipo.setColumns(20);
        txaGanadorEquipo.setRows(5);
        txaGanadorEquipo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ganador por Equipos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Sylfaen", 1, 14))); // NOI18N
        txaGanadorEquipo.setFocusable(false);
        jScrollPane3.setViewportView(txaGanadorEquipo);

        btnReiniciar.setBackground(new java.awt.Color(192, 229, 234));
        btnReiniciar.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        btnReiniciar.setText("Reiniciar Simulador");
        btnReiniciar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReiniciar.setFocusable(false);
        btnReiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReiniciarActionPerformed(evt);
            }
        });

        btnSalir.setBackground(new java.awt.Color(192, 229, 234));
        btnSalir.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        btnSalir.setText("Salir del Simulador");
        btnSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalir.setFocusable(false);
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
            .addGroup(layout.createSequentialGroup()
                .addGap(214, 214, 214)
                .addComponent(jLabel1)
                .addContainerGap(203, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnReiniciar)
                .addGap(139, 139, 139)
                .addComponent(btnSalir)
                .addGap(245, 245, 245))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReiniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        Competidor ganadorGeneral = oSimulacion.ganadorGeneral();
        ECategoriaCompetidor categoria = oSimulacion.ganadorCategoria();
        EAsignarEquipos equipos = oSimulacion.ganadorEquipo();
        txaGanadorCategoria.append("La categoria ganadora es: " + categoria.name() + "\nCon un tiempo de: " + oSimulacion.ganadorCategoriaTiempo());
        txaGanadorGeneral.append("El ganador general del ISW Grand-Go-Kart es: " + ganadorGeneral.getId() + "\nCon un tiempo de: " + ganadorGeneral.getTiempoTotal());
        txaGanadorEquipo.append("El Equipo ganador es: " + equipos.name() + "\nCon un tiempo de: " + oSimulacion.ganadorEquipoTiempo());
    }//GEN-LAST:event_formWindowOpened

    private void btnReiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReiniciarActionPerformed
        // TODO add your handling code here:
        oSimulacion.limpiarDatos();
        JOptionPane.showMessageDialog(this, "Simulacion reiniciada con exito.");
        this.dispose();
    }//GEN-LAST:event_btnReiniciarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReiniciar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea txaGanadorCategoria;
    private javax.swing.JTextArea txaGanadorEquipo;
    private javax.swing.JTextArea txaGanadorGeneral;
    // End of variables declaration//GEN-END:variables
}
